[package]
name = "profile_program"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.1"
borsh-derive = "1.5.1"
solana-program = "2.0.13"


[lib]
name = "profile_program"
crate-type = ["cdylib", "lib"]
