[package]
name = "ecomm_contract"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.1"
borsh-derive = "1.5.1"
solana-program = "2.0.11"

[lib]
name = "ecomm_contract"
crate-type = ["cdylib", "lib"]
